### ISSUE TITLE
Remove underlines between badge links

### ISSUE THREAD

**Issue by twiccox** [twiccox/portfolio#1]
# Description

As shown below, there's a blue underline between badge links.

<img width="908" alt="image" src="https://github.com/twiccox/portfolio/assets/12343599/6689af72-352d-4be0-a524-f864552382b0">

# Research

The HTML data attribute `data-a11y-link-underlines` is applied on root `html` tag.

```css
[data-a11y-link-underlines=true] .markdown-body a,
[data-a11y-link-underlines=true] .markdown-body a:hover,
[data-a11y-link-underlines=true] .commit-desc a,
[data-a11y-link-underlines=true] .commit-desc a:hover,
[data-a11y-link-underlines=true] .Link--inTextBlock,
[data-a11y-link-underlines=true] .Link--inTextBlock:hover {
    text-decoration: underline;
    text-underline-offset: 0.2rem;
}
```
